### ISSUE TITLE
Failed to convert from from kitti to voc

### ISSUE THREAD

**Issue by jjj9china** [umautobots/vod-converter#17]
what is the problem??
Failed to convert from from kitti to voc: Expected subdirectory training/image_2 within datasets/mydata-kitti.

**Comment by LucasVandroux** [comment]
In order to convert from KITTI to VOC, `vod_converter/kitti.py` needs to get the `width` and `height` of the images and therefore need to access them too. (cf. `vod_converter/kitti.py:_image_dimensions`)

You can create a symlink in your folder to the folder containing the images corresponding to the labels you are trying to convert: [How to symlink a file in Linux? [Stackoverflow]](https://stackoverflow.com/questions/1951742/how-to-symlink-a-file-in-linux)

**Comment by zssjh** [comment]
@jjj9china have you solved this problem?

**Comment by ghost** [comment]
it is solved
